- hosts: server
  vars:
  - image: asmarty/httpd-custom:icon
  tasks:
   - name: install python docker for ubuntu 
     apt:
      name:
       - python3
       - python-docker
      state: present
     when:
      - ansible_distribution == "Ubuntu"
   - name: Install python docker for centos
     yum:
      name: python-docker
      state: present
     when:
      - ansible_distribution == "CentOS"
   - name: pull image
     docker_image:
        name: "{{ image }}"
        state: present
   - name: create container
     docker_container:
        name: docker-ansible         
        state: started
        published_ports:
         - 8090:80
        image: "{{ image }}"
        recreate: yes
